import "./globals.css";
import Header from "./components/Header";

export const metadata = {
  title: "Blog App",
  description: "Generated by Techamnnih",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
